version: '3.8'

services:
  # BACKEND EN SPRING BOOT
  backend:
    build: .
    container_name: spring-backend
    ports:
      - "8080:8080"

  # FRONTEND EN REACT
  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  # BACKEND DEL TO-DO
  backend-todo:
    build: ./ToDo-Calidad-de-Software
    container_name: spring-backend-todo
    ports:
      - "8081:8080"

  # FRONTEND DEL TO-DO
  frontend-todo:
    build: ./ToDo-Calidad-de-Software/todo-frontend
    container_name: react-frontend-todo
    ports:
      - "3001:80"
    depends_on:
      - backend-todo